### PR TITLE
print style sheet for museums page

### PR DESCRIPTION
**Pull request by designmatty**
fix for #54

### CODE REVIEW

**Comment by CloudNiner** [comment]
Pulled this down, and things still look...off. Can you post a screenshot of what the print preview looks like on your machine?

**Comment by flibbertigibbet** [comment]
@sharph could you check this out? Not sure of the status of this.

**Comment by designmatty** [comment]
@jbranigan and I went through it yesterday. Admittedly it's not the most ideal layout. 

There were some bugs with nvd3 and nesting them within bootstrap tabs. Apparently the charts will scale down to about a quarter their actual size if their containing parent element is hidden via `display: none;`. After resolving that, even then, if you attempt to resize the chart (or any svg) via the print css you are met with less than optimal results.

**Comment by sharph** [comment]
@jbranigan 
[imls-broken-print.pdf](https://github.com/azavea/imls-museum-data/files/3971/imls-broken-print.pdf)

**Comment by sharph** [comment]
@designmatty I'd recommend against capitalizing URLs. They can be case sensitive.

**Comment by sharph** [comment]
Nevermind -- that's not in the styling, it's in the database, isn't it?

**Pull request merged**
