### PR TITLE
Feature/chart one

### PR DESCRIPTION
**Pull request by CloudNiner**
WIP branch to display bar charts. Pie charts and charts that display medians will need different handling. 

Not convinced that the workflow of raw data -> ACSAggregate -> nvd3 series transformation is the easiest way to go about this, open to other suggestions on how to clean this up without taking a ton of extra time on the task.

[Review on Reviewable](https://reviewable.io/reviews/azavea/imls-museum-data/13)

### CODE REVIEW

**Comment by CloudNiner** [comment]
screen shot 2015-07-20 at 3 59 10 pm

**Comment by sharph** [comment]
It might be nice to have a transformation step from tract arrays (data for a specific tract) into tract objects, where the variables are named and stored as properties of the object. This might make the code further down the line easier to follow.

+1

**Comment by CloudNiner** [comment]
Can you think of a case where we would want the data in the format in which it comes back from the API? If not, I can add the transformation you suggest to the `transformResponse` of the ACS API call.

**Comment by sharph** [comment]
No, I don't think there is a good reason we want the response in the "header-row, data-rows" format. The reason they cite for outputting in this format as opposed to objects with properties is that it is supposed to parse faster, but don't think that is actually a problem.

**Comment by CloudNiner** [comment]
Agree. I'll swap to the suggested format then, and rework the current charts to use it before merging.

**Comment by CloudNiner** [comment]
Updated, and fixed the bug where the chart in the household tab wouldn't draw properly when its drawn while the tab is hidden.

There could be some more significant refactoring done here in the TabControllers and the getACSRequest transforms, but I'm going to defer those in the interest of time, since they're not critical ATM.

**Pull request merged**
