### PR TITLE
Feature/design cleanup

### PR DESCRIPTION
**Pull request by designmatty**

### CODE REVIEW

**Comment by designmatty** [comment]
I've included some favicon images and a new map marker for the map. Neither have been implemented.

**Comment by CloudNiner** [comment]
We'll implement the map marker, can you add the appropriate link tags for the android/iphone favicons to the `index.html`?

**Comment by CloudNiner** [comment]
Otherwise +1, looks great

**Comment by designmatty** [comment]
Okay cool. I'll make sure to do that before merging

**Pull request merged**
